# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the test drivers.
#

# Please keep it alphabetically sorted

obj-$(CONFIG_DVB_VIDTV)			+= vidtv/

obj-$(CONFIG_VIDEO_VICODEC)		+= vicodec/
obj-$(CONFIG_VIDEO_VIM2M)		+= vim2m.o
obj-$(CONFIG_VIDEO_VIMC)		+= vimc/
obj-$(CONFIG_VIDEO_VIVID)		+= vivid/
