/*
 * Copyright (C) 2012 NVIDIA CORPORATION.  All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#include "mc.h"

static const struct tegra_mc_client tegra20_mc_clients[] = {
	{ .name = "display0a" },
	{ .name = "display0ab" },
	{ .name = "display0b" },
	{ .name = "display0bb" },
	{ .name = "display0c" },
	{ .name = "display0cb" },
	{ .name = "display1b" },
	{ .name = "display1bb" },
	{ .name = "eppup" },
	{ .name = "g2pr" },
	{ .name = "g2sr" },
	{ .name = "mpeunifbr" },
	{ .name = "viruv" },
	{ .name = "avpcarm7r" },
	{ .name = "displayhc" },
	{ .name = "displayhcb" },
	{ .name = "fdcdrd" },
	{ .name = "g2dr" },
	{ .name = "host1xdmar" },
	{ .name = "host1xr" },
	{ .name = "idxsrd" },
	{ .name = "mpcorer" },
	{ .name = "mpe_ipred" },
	{ .name = "mpeamemrd" },
	{ .name = "mpecsrd" },
	{ .name = "ppcsahbdmar" },
	{ .name = "ppcsahbslvr" },
	{ .name = "texsrd" },
	{ .name = "vdebsevr" },
	{ .name = "vdember" },
	{ .name = "vdemcer" },
	{ .name = "vdetper" },
	{ .name = "eppu" },
	{ .name = "eppv" },
	{ .name = "eppy" },
	{ .name = "mpeunifbw" },
	{ .name = "viwsb" },
	{ .name = "viwu" },
	{ .name = "viwv" },
	{ .name = "viwy" },
	{ .name = "g2dw" },
	{ .name = "avpcarm7w" },
	{ .name = "fdcdwr" },
	{ .name = "host1xw" },
	{ .name = "ispw" },
	{ .name = "mpcorew" },
	{ .name = "mpecswr" },
	{ .name = "ppcsahbdmaw" },
	{ .name = "ppcsahbslvw" },
	{ .name = "vdebsevw" },
	{ .name = "vdembew" },
	{ .name = "vdetpmw" },
};

static const struct tegra_mc_module tegra20_mc_modules[] = {
	[TEGRA_MEMORY_CLIENT_AVP]	= { .hw_id =  0, .valid = true },
	[TEGRA_MEMORY_CLIENT_DC]	= { .hw_id =  1, .valid = true },
	[TEGRA_MEMORY_CLIENT_DCB]	= { .hw_id =  2, .valid = true },
	[TEGRA_MEMORY_CLIENT_EPP]	= { .hw_id =  3, .valid = true },
	[TEGRA_MEMORY_CLIENT_2D]	= { .hw_id =  4, .valid = true },
	[TEGRA_MEMORY_CLIENT_HOST1X]	= { .hw_id =  5, .valid = true },
	[TEGRA_MEMORY_CLIENT_ISP]	= { .hw_id =  6, .valid = true },
	[TEGRA_MEMORY_CLIENT_MPCORE]	= { .hw_id =  7, .valid = true },
	[TEGRA_MEMORY_CLIENT_MPEA]	= { .hw_id =  8, .valid = true },
	[TEGRA_MEMORY_CLIENT_MPEB]	= { .hw_id =  9, .valid = true },
	[TEGRA_MEMORY_CLIENT_MPEC]	= { .hw_id = 10, .valid = true },
	[TEGRA_MEMORY_CLIENT_3D]	= { .hw_id = 11, .valid = true },
	[TEGRA_MEMORY_CLIENT_PPCS]	= { .hw_id = 12, .valid = true },
	[TEGRA_MEMORY_CLIENT_VDE]	= { .hw_id = 13, .valid = true },
	[TEGRA_MEMORY_CLIENT_VI]	= { .hw_id = 14, .valid = true },
};

const struct tegra_mc_soc tegra20_mc_soc = {
	.clients = tegra20_mc_clients,
	.num_clients = ARRAY_SIZE(tegra20_mc_clients),
	.num_address_bits = 32,
	.client_id_mask = 0x3f,
	.tegra20 = true,
	.modules = tegra20_mc_modules,
	.num_modules = ARRAY_SIZE(tegra20_mc_modules),
	.reg_client_ctrl = 0x100,
	.reg_client_hotresetn = 0x104,
	.reg_client_flush_status = 0x140,
};
