obj-$(CONFIG_ACER_A500_EC_BATTERY)	+= a500-battery.o
obj-$(CONFIG_ACER_A500_EC_LEDS)		+= a500-leds.o
obj-$(CONFIG_ACER_A500_EC_LEGACY_SYSFS)	+= a500-legacy-sysfs.o
obj-$(CONFIG_ACER_A500_EC_MFD)		+= a500-ec.o
