# SPDX-License-Identifier: GPL-2.0-only
# Makefile for lib/ function selftests

# No binaries, but make sure arg-less "make" doesn't trigger "run_tests"
all:

TEST_PROGS := printf.sh bitmap.sh prime_numbers.sh strscpy.sh slub.sh

include ../lib.mk
