name: checkpatch review
on: [pull_request]
jobs:
  my_review:
    name: checkpatch review
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 150
    - name: Run checkpatch review
      uses: webispy/checkpatch-action@master
      env:
        CHECKPATCH_COMMAND: checkpatch.pl --no-tree --strict
